CREATE DATABASE AliadaVentasDB;
GO

USE AliadaVentasDB;
GO

-- Tabla de categorías
CREATE TABLE DIM_CATEGORY (
    CATEGORY INT PRIMARY KEY,
    CATEGORYNAME NVARCHAR(100)
);

-- Tabla de productos
CREATE TABLE DIM_PRODUCT (
    MANUFACTURER NVARCHAR(100) PRIMARY KEY,
    BRAND NVARCHAR(100),
    ITEM INT,
	ITEM_DESCRIPTION NVARCHAR(100),
	CATEGORY INT,
	FORMAT VARCHAR(100),
	ATTR1 NVARCHAR(100),
	ATTR2 NVARCHAR(100),
    ATTR3 NVARCHAR(100),
    FOREIGN KEY (CATEGORY) REFERENCES DIM_CATEGORY(CATEGORY)
);

-- Tabla de segmentos
CREATE TABLE DIM_SEGMENT (
    SEGMENT_ID INT PRIMARY KEY,
    ATTR1 NVARCHAR(100),
	ATTR2 NVARCHAR(100),
    ATTR3 NVARCHAR(100),
	FORMAT VARCHAR(100),
	SEGMENT VARCHAR(100)
);

-- Tabla de calendario
CREATE TABLE DIM_CALENDAR (
    WEEK INT PRIMARY KEY,
	YEAR INT,
    MONTH INT,
    WEEK_NUMBER INT,
	DATE DATE
);

-- Tabla de hechos (ventas)
CREATE TABLE FACT_SALES (
    WEEK INT PRIMARY KEY,
    ITEM INT,
    TOTAL_UNIT_SALES DECIMAL,
    TOTAL_VALUE_SALES DECIMAL,
    TOTAL DECIMAL,
    REGION NVARCHAR(100),
    FOREIGN KEY (WEEK) REFERENCES DIM_CALENDAR(WEEK)
);

-- BULK INSERT corregido
BULK INSERT DIM_CATEGORY
FROM 'C:\BasesDeDatos\DIM_CATEGORY.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\r\n',
    FIRSTROW = 2
);

BULK INSERT DIM_PRODUCT
FROM 'C:\BasesDeDatos\DIM_PRODUCT.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\r\n',
    FIRSTROW = 2
);

BULK INSERT DIM_SEGMENT
FROM 'C:\BasesDeDatos\DIM_SEGMENT.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\r\n',
    FIRSTROW = 2
);

BULK INSERT DIM_CALENDAR
FROM 'C:\BasesDeDatos\DIM_CALENDAR.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\r\n',
    FIRSTROW = 2
);


BULK INSERT FACT_SALES
FROM 'C:\BasesDeDatos\FACT_SALES.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\r\n',
    FIRSTROW = 2
);

-- Verificar datos cargados
SELECT TOP 10 * FROM DIM_CATEGORY;
SELECT TOP 10 * FROM DIM_PRODUCT;
SELECT TOP 10 * FROM DIM_SEGMENT;
SELECT TOP 10 * FROM DIM_CALENDAR;
SELECT TOP 10 * FROM FACT_SALES;

SELECT 
    dc.CATEGORYNAME,
    SUM(fs.TOTAL_VALUE_SALES) AS TotalVentas
FROM FACT_SALES fs
JOIN DIM_PRODUCT dp ON fs.ITEM = dp.ITEM
JOIN DIM_CATEGORY dc ON dp.CATEGORY = dc.CATEGORY
GROUP BY dc.CATEGORYNAME
ORDER BY TotalVentas DESC;

SELECT 
    fs.REGION,
    dc.YEAR,
    SUM(fs.TOTAL_VALUE_SALES) AS TotalVentas
FROM FACT_SALES fs
JOIN DIM_CALENDAR dc ON fs.WEEK = dc.WEEK
GROUP BY fs.REGION, dc.YEAR
ORDER BY fs.REGION, dc.YEAR;

SELECT 
    cat.CATEGORYNAME,
    cal.MONTH,
    SUM(fs.TOTAL_VALUE_SALES) AS TotalVentas
FROM FACT_SALES fs
JOIN DIM_CALENDAR cal ON fs.WEEK = cal.WEEK
JOIN DIM_PRODUCT p ON fs.ITEM = p.ITEM
JOIN DIM_CATEGORY cat ON p.CATEGORY = cat.CATEGORY
GROUP BY cat.CATEGORYNAME, cal.MONTH
ORDER BY cat.CATEGORYNAME, cal.MONTH;

SELECT 
    fs.REGION,
    cat.CATEGORYNAME,
    SUM(fs.TOTAL_VALUE_SALES) AS TotalVentas
FROM FACT_SALES fs
JOIN DIM_PRODUCT dp ON fs.ITEM = dp.ITEM
JOIN DIM_CATEGORY cat ON dp.CATEGORY = cat.CATEGORY
GROUP BY fs.REGION, cat.CATEGORYNAME
ORDER BY fs.REGION, TotalVentas DESC;

SELECT 
    seg.SEGMENT,
    seg.FORMAT,
    SUM(fs.TOTAL_VALUE_SALES) AS TotalVentas
FROM FACT_SALES fs
JOIN DIM_PRODUCT dp ON fs.ITEM = dp.ITEM
JOIN DIM_SEGMENT seg ON dp.FORMAT = seg.FORMAT
GROUP BY seg.SEGMENT, seg.FORMAT
ORDER BY TotalVentas DESC;
